### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by pbustos** [ozomer/node-red-contrib-mongodb2#1]
Hi, 
very nice work. I am having trouble putting it to work. Is somewhere an  example of a flow using your node?

Thanks

Pablo

**Comment by ozomer** [comment]
I hope this will help: http://flows.nodered.org/flow/b44ff06a385743b7bbf7

**Comment by pbustos** [comment]
Thanks a lot.

I worked like charm.

Pablo

On Sun, Mar 29, 2015 at 12:42 AM, Oren Zomer notifications@github.com
wrote:

> I hope this will help: http://flows.nodered.org/flow/b44ff06a385743b7bbf7
> 
> On 29 March 2015 at 02:20, pbustos notifications@github.com wrote:
> 
> > Hi,
> > very nice work. I am having trouble putting it to work. Is somewhere an
> > example of a flow using your node?
> > 
> > Thanks
> > 
> > Pablo
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ozomer/node-red-contrib-mongodb2/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ozomer/node-red-contrib-mongodb2/issues/1#issuecomment-87330967
> .

## 

Pablo Bustos García de Castro
Laboratorio de Robótica y Visión Artificial
http://robolab.unex.es
Escuela Politécnica
Universidad de Extremadura
Avda de la Universidad s/n
Cáceres 10003
Phone: +34 927 257259
Fax: +34 927 257203
