### ISSUE TITLE
Support for Environment Variables

### ISSUE THREAD

**Issue by anandrajneesh** [ozomer/node-red-contrib-mongodb2#11]
I wanted to externalize the connection string for MongoDB as I have to run my flows on different setups/environments, but while referring to env variable as $(connectionString) it does not work. 
**node-red-node-mongodb** node honors $( ) notation and the variables are replaced from environment variables if set.  Is there something similar available for this node too ?

**Comment by ozomer** [comment]
Please see: https://github.com/ozomer/node-red-contrib-mongodb2/issues/10#issuecomment-282415261 .
Using a storage-module will allow you to make every configuration depend on environment variables
