### ISSUE TITLE
Node label is undefined:undefined/undefined although connection works

### ISSUE THREAD

**Issue by ssadams11** [ozomer/node-red-contrib-mongodb2#12]
![screen shot 2017-07-12 at 2 43 30 pm](https://user-images.githubusercontent.com/5204570/28134278-7ec07342-6710-11e7-9443-233fc034e97d.png)

**Comment by ssadams11** [comment]
I've seen this with both a local mongoldb connection and with Compose for Mongodb on Bluemix

**Comment by ozomer** [comment]
Happened when the config node did not have a specified name.
Fixed in version 0.5.6 👍 - using the uri for the label (with best-effort to remove credentials). 

P.S. @ssadams11 "Mongol DB" could be a nice extension to "Mongo DB" 😄
