### ISSUE TITLE
Lookup? 

### ISSUE THREAD

**Issue by hamild** [ozomer/node-red-contrib-mongodb2#14]
Is there a way to perform $lookup ?  As I understand it, this is the equivalent of a JOIN in SQL.  I am very new to MongoDB, so apologies in advance if this is off topic.

**Comment by ozomer** [comment]
You can find all the operations here: http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html .
The node-red-contrib-mongodb2 node simply calls those functions, using `msg.payload` for parameters (`msg.payload[0]` for the first parameter, `msg.payload[1]` for the second parameter, etc.).
