### ISSUE TITLE
deleting collection by ObjectID

### ISSUE THREAD

**Issue by RafOXxxx** [ozomer/node-red-contrib-mongodb2#26]
I am not able to delete documents by "_id" using the `deleteOne()` method. I presume it's because I am passing the id as a string and not as an `ObjectId` object.
But saying that, how do I turn a string into an `ObjectId` object?

**Comment by ozomer** [comment]
Install mongodb and use `mongodb.ObjectId()`. Maybe `{ "$id": "..." }` will also work but I'm not sure.

**Comment by RafOXxxx** [comment]
Thanks for the response, the `{ "$id": "..." }` approach did not work for me. 
I installed **node-red-contrib-objectid**, that made it work. 

Are there newer example-flows for **node-red-contrib-mongodb2**? Because I also have trouble sorting my  results.
In examples I have seen so far people just do:

`msg.sort = { time: -1 } `

but that does not seem to work anymore.

**Comment by ozomer** [comment]
Great, I didn't know node-red-contrib-objectid exists. I just install mongodb and use `const { ObjectId } = require('mongodb');`.
node-red-contrib-mongodb2 only looks at the msg.payload param - which should be an array of arguments that are passed to the [mongodb](http://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#find) operations. For example, the find operation can accept two parameters: `query` and `options`. In options you can use "sort", so you may want to create a msg with a payload that looks like:
`[{ somequeryfield: somevalue }, { sort: { time: -1 }}]`.

**Comment by RafOXxxx** [comment]
Thank god! I have been googling for this information for a couple of days now and somehow could only find very misleading stuff.
I can't thank you enough **ozomer**!  😃 👍

**Comment by ozomer** [comment]
You're welcome @RafOXxxx !
