### ISSUE TITLE
msg.projection does not work

### ISSUE THREAD

**Issue by number005** [ozomer/node-red-contrib-mongodb2#27]
**operation: find.toArray**

The function before the mongodb3 node containts:
```
msg.payload = {"age":50}
msg.projection = {"firstName":1}

return msg;
```

Anyhow, the result includes all fields and not only the firstName like I wish.

**Comment by ozomer** [comment]
Try: `msg.payload = [{"age": 50}, {"fields": {"firstName": 1}}]; return msg;`

**Comment by Digital-Thor** [comment]
Not sure if the question is for Mongo V3, but according to the [V3 Docs](http://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#find), `fields` is deprecated.  I found this structure works for me:

```
msg.payload =  [
    { age: 50},
    { 
        projection : {firstname: 1},
        limit: 5
    }
];
return msg;
```

In this case, Mongo should return only the `firstname` field, for up to a maximum of 5 results.
