### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by fcabrera23** [ozomer/node-red-contrib-mongodb2#29]
Hi I'm using this node with Node-Red v.0.18.7 and trying to update a document  using the following function

var newMsg = msg;
newMsg.payload= {
    query: { "imei": msg.payload.imei },
    options : {upsert : true},
    update: { $set: msg.payload }
};
return newMsg;

However nothing gets modified. Any idea?

**Comment by ozomer** [comment]
Look at the function [here](https://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#updateOne), it receives 3 parameters.
you should do:
```
var newMsg = msg;
newMsg.payload= [
  { "imei": msg.payload.imei },
  { $set: msg.payload },
  {upsert : true}
];
return newMsg;
```
