### ISSUE TITLE
MongoDB3 trouble with InsertMany

### ISSUE THREAD

**Issue by germancmartinez** [ozomer/node-red-contrib-mongodb2#33]
Hi,

I´m having problems with the InsertMany method. I´m getting the error "MongoError: docs parameter must be an array of documents". I have tried putting the document array in the msg.payload and msg.payload.docs, but I'm always getting this error. 
Any help is welcome!
Thanks!

**Comment by jomel** [comment]
when message payload is an array, each array element is interpreted as a parameter to the selected operation. eg when `operation= "update"`, `message.payload=[{surname:"smith"}, {"surname":"Smith"}, {"multi":true}]`

since for you are wanting to supply an array as a single parameter, you should wrap it in a second array: 
 `message.payload=[[1,2,3,4]]` and not `message.payload=[1,2,3,4]`

**Comment by mrdelarosatorres** [comment]
> when message payload is an array, each array element is interpreted as a parameter to the selected operation. eg when `operation= "update"`, `message.payload=[{surname:"smith"}, {"surname":"Smith"}, {"multi":true}]`
> 
> since for you are wanting to supply an array as a single parameter, you should wrap it in a second array:
> `message.payload=[[1,2,3,4]]` and not `message.payload=[1,2,3,4]`

Thanks!

**Comment by cudochinigi** [comment]
for insertMany
✗ msg.payload = [ { "name" : "Luffy" , "value" : 1} , { "name" : "Zoro" , "value" : 2 } ]
✓ msg.payload = [ [ { "name" : "Luffy" , "value" : 1} , { "name" : "Zoro" , "value" : 2 } ] ]

**Comment by VINITARORA-21** [comment]
this is the correct format  db.collectionname.insertMany([ {} , {} , {}  ])

collectionname would be your collection u have created in ur database

{ } inside this your objects would be there 
eg:

try {
   db.products.insertMany( [
      { _id: 13, item: "envelopes", qty: 60 },
      { _id: 13, item: "stamps", qty: 110 },
      { _id: 14, item: "packing tape", qty: 38 }
   ] );
} catch (e) {
   print (e);
}

refer this

https://www.mongodb.com/docs/manual/reference/method/db.collection.insertMany/#mongodb-method-db.collection.insertMany

**Comment by DouaaELKORTI** [comment]
Thanks...it worked
