### ISSUE TITLE
get collections list

### ISSUE THREAD

**Issue by slkow** [ozomer/node-red-contrib-mongodb2#39]
I would like to be able to get array with all collections in db. Could you add that operation?

**Comment by jomel** [comment]
I presume you are referring to the equivalent of `db.listCollections().toArray()` : [driver docs link](http://mongodb.github.io/node-mongodb-native/3.0/api/Db.html#listCollections) ?

**Comment by slkow** [comment]
Yes.

wt., 26 mar 2019, 16:47 użytkownik jomel <notifications@github.com> napisał:
